In [9]:
import pandas as pd

In [10]:
df = pd.DataFrame ({"size":["xl","m","l","xl","m","l","s","s","xl","xl","m","l"]})

In [11]:
df.head(3)

  size
0   xl
1    m
2    l

In [13]:
ord_data =[["s","m","l","xl"]]

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [23]:
oe = OrdinalEncoder(categories=ord_data)
oe.fit_transform(df[["size"]])

array([[3.],
       [1.],
       [2.],
       [3.],
       [1.],
       [2.],
       [0.],
       [0.],
       [3.],
       [3.],
       [1.],
       [2.]])

In [25]:
df["size_en"] = oe.fit_transform(df[["size"]])

In [26]:
df

   size  size_en
0    xl      3.0
1     m      1.0
2     l      2.0
3    xl      3.0
4     m      1.0
5     l      2.0
6     s      0.0
7     s      0.0
8    xl      3.0
9    xl      3.0
10    m      1.0
11    l      2.0

In [27]:
#map funtion

In [28]:
ord_d ={"s":0,"m":1,"l":2,"xl":3}

In [30]:
df["size_e"]= df["size"].map(ord_d)

In [31]:
df

   size  size_en  size_e
0    xl      3.0       3
1     m      1.0       1
2     l      2.0       2
3    xl      3.0       3
4     m      1.0       1
5     l      2.0       2
6     s      0.0       0
7     s      0.0       0
8    xl      3.0       3
9    xl      3.0       3
10    m      1.0       1
11    l      2.0       2